name = "manzi-lucky-portfolio"
account_id = ""
workers_dev = true
compatibility_date = "2024-01-01"

main = "src/worker.js"
assets = { directory = "./dist", binding = "ASSETS", run_on = "list" }

[[routes]]
pattern = "manzi-lucky.dev/*"
zone_id = ""
